PROTOCOL_VERSION = "powerchain-renewable-proof/1"
QUALITY_BPS_MAX = 10_000
DEFAULT_QUALITY_BPS = 10_000
DEFAULT_SAMPLE_INTERVAL_SECONDS = 5
DEFAULT_PROOF_INTERVAL_SECONDS = 60
DEFAULT_HEARTBEAT_INTERVAL_SECONDS = 30
DEFAULT_QUEUE_LIMIT = 100_000
