[package]
name = "powerchain-miner"
version = "1.0.0"
description = "PowerChain Miner reward protocol for verified hardware work"
edition = "2021"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "lib"]
name = "powerchain_miner"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = "1.1.2"
anchor-spl = { version = "1.1.2", features = ["token_2022", "token_2022_extensions"] }
